apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    env:
    - name: CHANNELNAME
      valueFrom:
        configMapKeyRef:
          name: demo-configmap
          key: channel.name
    - name: 
      valueFrom:
        configMapKeyRef: CHANNELOWNER
          name: demo-configmap
          key: channel.owner

         