apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: helloworld-cronjob
spec:
  schedule: "* * * * *"
#  suspend: true
#  successfulJobsHistoryLimit: 0
#  failedJobsHistoryLimit: 0
#  concurrencyPolicy: Allow or forbod or Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox
            command: ["echo", "hello kubernetes"]
          restartPolicy: Never