apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
#  backoffLimit: 2
#  ttlSecondsAfterFinished: 100
#  completions: 3
#  parallelism: 2
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
