apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    run: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      volumes:
        - name: www
          persistentVolumeClaim:
            claimName: pvc-nfs-pv1
      containers:
      - name: nginx-deploy
        image: nginx
        volumeMounts:
          - name: www
            mountPath: /usr/share/nginx/html 