apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: mysecret
  containers:
  - name: myapp
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    volumeMounts:
    - name: secret-volume
      mountPath: /mydata   

