apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deploy
  labels:
    app: java-app
spec:
  selector:
    matchLabels:
      app: java-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: sanjaygs953/my-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests: 
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"



